
service: iddispenser

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2
  stage: ${opt:stage, 'dev'}

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: awsh-${self:provider.stage}-iddispenser
        AttributeDefinitions:
          - AttributeName: idtag
            AttributeType: S
        KeySchema:
          - AttributeName: idtag
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  dispense:
    handler: handler.dispense
