FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# AWSHome

AWSHome API.

## Records  [/devices/{did}/journals/{jid}/records]

+ Parameters
    + did: `adv34dv` (string, required) - Device ID.
    + jid: `1` (string, required) - Journal ID.
        
### Create a new record [POST]

Devices can report a new record into their journals.

+ Request (application/json)

        {
            "version": 1,
            "timestamp": 1567607026,
            "type": "TEMP",
            "value": "22"
        }

+ Response 201 (application/json)

    + Headers

            Location: /devices/{did}/journals/{jid}/records

    + Body

            {
               "did": "adv34dv",
                "jid": "1",
                "timestamp": 1567607026
            }