service: aws-home-api
app: aws-home
frameworkVersion: "=1.48.2"
package:
  individually: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  environment:
    SLS_STAGE: ${self:provider.stage}
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"

plugins:
  - serverless-bundle
  - serverless-dynamodb-local
  - serverless-offline

functions:
  devices-journals-entries-create:
    handler: http/devices-journals-entries.create
    events:
      - http:
          path: /api/devices/{did}/journals/{jid}/entries/
          method: post
          request:
            parameters:
              paths:
                - did: true
                - jid: true
  devices-journals-entries-list:
    handler: http/devices-journals-entries.list
    events:
      - http:
          path: /api/devices/{did}/journals/{jid}/entries/
          method: get
          request:
            parameters:
              paths:
                - did: true
                - jid: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: awsh-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: uid
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: uid
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  dynamodb:
    stages:
      - test
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: awsh-test
            sources: [./database/seeds/awsh-test.json]

