service: awsh-api

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2
  stage: ${opt:stage, 'dev'}
  environment:
    SLS_STAGE: ${self:provider.stage}

plugins:
  - serverless-dotenv-plugin
  - serverless-bundle

functions:
  devices-journals-record-create:
    handler: handlerDevicesJournalsRecords.create
    events:
      - http:
          path: /api/devices/{did}/journals/{jid}/records/
          method: post
          request:
            parameters:
              paths:
                - did: true
                - jid: true
  devices-journals-records-list:
    handler: handlerDevicesJournalsRecords.list
    events:
      - http:
          path: /api/devices/{did}/journals/{jid}/records/
          method: get
          request:
            parameters:
              paths:
                - did: true
                - jid: true

